#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the machine
hostname=$(hostname)

# Configure Nginx to include the custom HTTP response header
sudo sed -i '/^http {/a \add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart

