#!/bin/bash

# Update the package index
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo touch /etc/haproxy/haproxy.cfg

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 147330-web-01:80 check
    server web-02 147330-web-02:80 check
EOT

# Make sure HAProxy can be managed via an init script
sudo systemctl enable haproxy.service

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy.service

